name: Build and Deploy to Render

on:
  push:
    branches:
      - master

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: samuel009/gatekeeper:latest

      - name: Trigger Render deployment
        uses: fjogeleit/http-request-action@v1
        with:
          url: https://api.render.com/deploy/srv-d13b6tbe5dus73ej2dcg?key=CJ96xUfvZ8s # Your Render service deploy URL
          method: POST
          headers: |
            Authorization: Bearer ${{ secrets.RENDER_API_KEY }}
            Content-Type: application/json
          body: '{}'
